### ISSUE TITLE
add an option to set path to mpv and mediainfo(gui)

### ISSUE THREAD

**Issue by sdsucks** [jlw4049/FFMPEG-Audio-Encoder#13]
for people like me who already have both installed

**Comment by jlw4049** [comment]
I'll add this to my to do list

**Comment by jlw4049** [comment]
I wanted to update, I'll be starting work on this sometime this evening/tomorrow. I'll add support to choose the path to most of the included apps

**Comment by jlw4049** [comment]
Posting back, features has been added in v3.1

https://github.com/jlw4049/FFMPEG-Audio-Encoder/releases/tag/3.1
