### ISSUE TITLE
A small bug

### ISSUE THREAD

**Issue by serkan1247** [jlw4049/FFMPEG-Audio-Encoder#14]
Hi, your software has a small bug.  After  a few conversions software doesn't work  unless you check  ''Shells Stays Open (Debug) '' under Options--Shell Options.
Do you considering to add ''save as user preset'' option
Keep your good work.Thanks.

**Comment by jlw4049** [comment]
I've been working A LOT of hours, I'm going to start trying to do some work on this today

**Comment by jlw4049** [comment]
Also could you explain to me what happens when the program just stops working? I'd like to fix the bug where it quits after so many conversions.

**Comment by jlw4049** [comment]
Feature added as per requested

https://github.com/jlw4049/FFMPEG-Audio-Encoder/releases/tag/3.2
