### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by kaze5** [jlw4049/FFMPEG-Audio-Encoder#16]
Hello! First of all I want to thank for all the work that was done. The suggestion I have, which I assume might be relevant to the project, is to add lossless delay/cut using stuff like eac3to (can have various usages such as merging two AC3 audios that have the same setup as in bitrate and channels), m4acut (for M4A AAC files), DelayCut (for DTS, AC3 and E-AC3 files) and if I'm not mistaken ffmpeg allows to delay some of the mentioned formats losslessly too (and some more) so it can be used instead. I also had an idea on basic AC3 lossless editing (as in cutting/delaying mid-duration), if you're interested I can explain/show an example.

**Comment by jlw4049** [comment]
I am open and interested to suggestions. I'll need to know how to do it and how it works of course first!

**Comment by kaze5** [comment]
Hey, that's great to hear! Lossless delaying/cutting isn't 100% precise due to codec limitations, so there's some factors to take into account. If there's any way I can help, I'm willing to.

**Comment by jlw4049** [comment]
Let me know if you need this still implemented later with 100% accuracy
