### ISSUE TITLE
Still showing as threats with VirusTotal

### ISSUE THREAD

**Issue by vonH** [jlw4049/FFMPEG-Audio-Encoder#17]
Based on latest compiled release: https://www.virustotal.com/gui/file/fc3500507d6bc50f5172f3e2ee336e00a088f84ecc24199651a32ee089990de3/detection

**Comment by jlw4049** [comment]
This is a fight that I can never truly win. I'll attempt to follow a guide and compile a custom version of pyinstaller to deal with this on windows. I'll take a look at this tomorrow.

**Comment by jlw4049** [comment]
The threats you are showing are indeed "false positives" 
The only OS I'm worried about is Windows to be honest. Are you having a virus detected within windows?

**Comment by vonH** [comment]
Hello @jlw4049,
I apologise for missing the notifications containing your updates, and would like to thank you for resolving this issue in a structured, professional and timely manner (_that is not meant to be patronising and I apologise if it comes across that way_). Additionally, As I write this, I can confirm your hard work has removed false positive detections from all 59 active heuristic engines used by VirusTotal, as well as a fully update-to-date Windows Security suite provided with Windows 11 (this previously also reported a false positive).

Once again, thank you and I hope you're staying safe given the current global situation.

Cheers,
Piers

**Comment by jlw4049** [comment]
> Hello @jlw4049, I apologise for missing the notifications containing your updates, and would like to thank you for resolving this issue in a structured, professional and timely manner (_that is not meant to be patronising and I apologise if it comes across that way_). Additionally, As I write this, I can confirm your hard work has removed false positive detections from all 59 active heuristic engines used by VirusTotal, as well as a fully update-to-date Windows Security suite provided with Windows 11 (this previously also reported a false positive).
> 
> **Edit**: _When submitting this report, I was using Windows 10 on a 6700K @ 4.4 GHz. Since then, I've upgraded to a 5900X and a clean install of Windows 11. The reason I mention this is not to brag, but to convey the improved scalability provided with the latest version. I realise this is partly based on newer FFmpeg builds, but it's also down to your programming and optimisations. I have a couple of suggestions and concerns which I will report in a new ticket._
> 
> Once again, thank you and I hope you're staying safe given the current global situation.
> 
> Cheers, Piers

No problem, researching it for a while seemed like there was no way to fix it. Then I came across a thread where I was able to actually compile my own version of pyinstaller x64 bit and it virtually removed every false positive. I'm glad I was able to figure it out!
