### ISSUE TITLE
Change FFmpeg build to GyanD's "essentials" compile

### ISSUE THREAD

**Issue by vonH** [jlw4049/FFMPEG-Audio-Encoder#18]
Hello,

I would suggest using the "essentials" GPLv3 build of FFmpeg by @GyanD. From a brief look, it appears to contain all the libraries required for FFMPEG-Audio-Encoder, but with an executable size reduction of 35.65%; this translates to ~115 MB being reduced to ~74 MB).

You can find the source and compiled releases [here](https://github.com/GyanD/codexffmpeg/releases/tag/2022-02-10-git-b6bb6b9f22), and more information [here](https://www.gyan.dev/ffmpeg/builds/#about-these-builds).

Regards,
Piers

**Comment by jlw4049** [comment]
I plan to do some work soon to the program. I have some things I'd like to do, a new feature among other things. I will test with the essential build and as long as it supports all the codecs then I will change the ffmpeg to that. A reduction in file size would be great. Thanks for bringing this to my attention.

**Comment by jlw4049** [comment]
I did some testing, the essential build has everything that is needed and I will certainly add it to the program in place of the full ffmpeg build. Thank you for pointing this out!
