### ISSUE TITLE
Batch converter not working anymore

### ISSUE THREAD

**Issue by PODxt** [jlw4049/FFMPEG-Audio-Encoder#21]
Holà, I updated FFMPEG-Audio-Encoder to its latest version but unfortunately I can't make the batch converter work anymore. I have to stay on version 3.34 where everything works as expected.

What I do is open the Batch Processor, 
select a folder with mkv files in it, 
select mkv in common extensions
set codec to AC3, downmix to stereo, set bitrate to 448k and Apply
select a Save directory and click on Start Batch Jobs.

On 3.34 everything works but not with the latest version.

**Comment by jlw4049** [comment]
I'm currently in the middle of re-write, the program will have many new changes and additions! 
I'm actually in the process, as I'm typing you, re-programming the batch encoder. The plans are to make it work a lot better then before. 

The program will be different in some ways, but will still do everything it did before, but better!

Thank you for reporting this bug, I'm hoping to get this done this week!

**Comment by PODxt** [comment]
Cool, that's awesome, I enjoy this program and the "Last Settings Used" feature is a real time saver! I just wanted to point out this bug with the Batch converter but there's no rush as 3.34 is still working great for me.

**Comment by PODxt** [comment]
Cool, that's awesome, I enjoy this program and the "Last Settings Used" feature is a real time saver! I just wanted to point out this bug with the Batch converter but there's no rush as 3.34 is still working great for me.

**Comment by jlw4049** [comment]
You'll be glad to know, that I've improved that feature! There is now a mini track selection window, when you use that, if audio track count is greater than 1! Which allows you to chose the track you want to encode with your last used settings.

**Comment by PODxt** [comment]
Wooo can't wait for it haha

**Comment by jlw4049** [comment]
Fixed with new and improved batch encoder/job menu

e8f2c59b0845dc84204b48f99bfe0cdb99198c91

**Comment by jlw4049** [comment]
Version 4.0 is out now, is has a new batch processing window/method
https://github.com/jlw4049/FFMPEG-Audio-Encoder/releases/tag/4.0
