### ISSUE TITLE
Youtube-dl not working in v4

### ISSUE THREAD

**Issue by PODxt** [jlw4049/FFMPEG-Audio-Encoder#24]
A quick message to let you know that Youtube-dl is not working in v4.
v3.34 is still rock solid and working as expected for me.

**Comment by jlw4049** [comment]
That is the only thing I didn't check, because I didn't make any changes to the code. Of course! lol
Will fix this now

**Comment by jlw4049** [comment]
Thanks for the bug report! 

Solved in the latest release https://github.com/jlw4049/FFMPEG-Audio-Encoder/releases/tag/4.01
