### ISSUE TITLE
Auto Encode Last Used Settings and wrong track selection

### ISSUE THREAD

**Issue by PODxt** [jlw4049/FFMPEG-Audio-Encoder#26]
When clicking Auto Encode Last Used Settings, then selecting a different track from track #1 (say track #2), and clicking Confirm Track and Start, the converted track will result in track #1 instead of #2.

**Comment by jlw4049** [comment]
I'm looking into this now

**Comment by jlw4049** [comment]
This is fixed in version 4.02 (will release this here in just a few minutes)
