### ISSUE TITLE
feature request: time modification with pitch change

### ISSUE THREAD

**Issue by anaveem** [jlw4049/FFMPEG-Audio-Encoder#29]
Hi, 

Would be great to have a GUI option to do time modification (e.g. 25 to 24) with pitch change. I read somewhere that this is done with -af "asetrate=48000*x" but adding that custom command (while leaving time mod in "original") didn't alter the pitch as necessary. If it's not on your to do list, what command might work?

Side note: the "save current settings" doesnt appear to work; my settings always go back to default.

Thanks.

**Comment by jlw4049** [comment]
I can look into the feature request after the weekend is over for you. 

Any chance you could drop accurate documentation on how this should be done?

Also the save current settings is different per codec. Could you please post a screen shot of the codec window with the settings you are attempting to save. Thanks!

**Comment by anaveem** [comment]
I read about **asetrate** here: https://forum.videohelp.com/threads/396848-PAL-DVD-change-frame-rate-25-23-976#post2580562
ProWo is the author of clever FFmpeg GUI, which does pitch correction but doesn't have qaac support. That's why I tried your program.

And never mind the save current settings comment I made. Tried it again and it works, sorry--false alarm.

**Comment by jlw4049** [comment]
I had about 15 minutes to look into this after work tonight. I'm going to look into it more tomorrow. 

However, I was successful in using a custom command line parameter. 

`-af asetrate=44100*3/4,atempo=4/3`

![image](https://user-images.githubusercontent.com/48299282/184567205-ed6ae99f-0a10-4670-9a12-7c10a93373d6.png)

This command enabled me to do what you wanted with **QAAC**. I'll need to read into this more and mess with it more tomorrow as I need to sleep tonight. 

Are you sure this is what you want? 

![image](https://user-images.githubusercontent.com/48299282/184567451-4139bbe9-b64e-4f70-a175-21ebc7bb4d94.png)

**Comment by anaveem** [comment]
Yes, thanks! I guess I wasn't using asetrate correctly. Using `-af asetrate=48000*24/25` with `atempo=25/24` works. 

(What I tried previously was `asetrate=4800*25/24`)

Would be great in the future to have this option built in. Alternatively, could you make it so that the 'save current settings' also saves the ffmpeg custom command?

**Comment by jlw4049** [comment]
I think, without changing too much code, it would be best to just save the custom command line vs adding a GUI option in for that for all codecs.

This will be a good way to do what you need without digging in too deeply. Let me see what I can do now, as I have a little free time.

**Comment by anaveem** [comment]
Yeah, no problem. The only issue is that the 'save current settings' does not save the ffmpeg command, so it has to be stored externally. Would be nice to be able to save the ffmpeg command as well. Thanks

**Comment by jlw4049** [comment]
I should have this feature done by the end of the day today for all codecs

**Comment by jlw4049** [comment]
Program now saves custom command line to the profile. Download [v4.04](https://github.com/jlw4049/FFMPEG-Audio-Encoder/releases/tag/4.04)

Feel free to post back here and let me know the results!
