### ISSUE TITLE
IndexError: list index out of range (line 127)

### ISSUE THREAD

**Issue by BassThatHertz** [jlw4049/FFMPEG-Audio-Encoder#3]
Currently this program is broken as you get the following error in the terminal when selecting a codec:
```
  File "C:\Users\H\Desktop\FFMPEG-Audio-Encoder\FFMPEG Audio Encoder.py", line 127, in track_count
    for i in range(int(str.split(track_count)[-1])):
IndexError: list index out of range
```

Edit: Also, I had a look at the code and it seems like my MP3 changes haven't been merged as you can see: https://i.imgur.com/DVkGQil.png
So you may want to make the changes manually.

**Comment by jlw4049** [comment]
You need the folders Apps/Runtime that is in the full release. This program relies on MediaInfo to display proper track information. You can get that here

https://github.com/jlw4049/FFMPEG-Audio-Encoder/releases

I had them on github, but it was complaining that I had .exe's in the github.

**Comment by jlw4049** [comment]
Is this something I should ignore and upload all the required files?

**Comment by BassThatHertz** [comment]
> You need the folders Apps/Runtime that is in the full release.

Just tried running **FFMPEG Audio Encoder v1.8.exe** and when I click on "Start Audio Job", a new terminal window opens for a split second and immediately closes.

**Comment by jlw4049** [comment]
Please go to the top, select the debug section, try the job again and let post the error in the cmd window.

**Comment by BassThatHertz** [comment]
```
[mp3 @ 0000016468edea00] Invalid stream specifier: a:0-c:a.
    Last message repeated 1 times
Stream map '0:a:0-c:a' matches no streams.
To ignore this, add a trailing '?' to the map
```
Looking at the error, it seems like the issue is that there is no space before `-c:a`.

**Comment by jlw4049** [comment]
This is fixed, I'm about to make a new commit/recompile. I'll post when it's done.

**Comment by jlw4049** [comment]
Try to pull latest commit/it has the included .exe's again, and test again. I need to fix a couple small issues with viewing the command line before I release a new release.

**Comment by BassThatHertz** [comment]
I will do that later. I did some more testing and a better way to describe the issue would've been to say that there is no space after `0:a:0`, as `-c:a` is not always what follows after. Anyway, when selecting Opus or QAAC, clicking on "Start Audio Job" does nothing.

**Comment by jlw4049** [comment]
This issue lies in this part of the code

```
    for i in range(int(str.split(track_count)[-1])):
        acodec_stream_track_counter[f'Track {i + 1}'] = f' -map 0:a:{i} '
```

In the release you have, there is no space after '{i}'

**Comment by BassThatHertz** [comment]
Makes sense, and the Opus/QAAC issue does not apply to the latest commit, so that's good.

**Comment by jlw4049** [comment]
Is this issue still happening on the MP3 codec with the latest commit?

**Comment by BassThatHertz** [comment]
Yes, I can see that the changes have been made in the latest version of the file.
