### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by peppersgc** [jlw4049/FFMPEG-Audio-Encoder#31]
**Describe the bug**
Got a traceback error while batch encoding on a 320 kb/s mp3 into a 192 kb/s m4a (qaac).

**To Reproduce**
1. Added the mp3's to batch.
2. Chose qaac as codec, and set it to 192 kb/s, changed to Constrained VBR, and checked High Efficiency. Everything else was default.
3. Clicked Start All Jobs.
4. See Additional Context

**Expected behavior**
Encode the entire batch of mp3's.

**Screenshots**
N/A

**Additional context**
Error Console.
Exception in thread Thread-34:Traceback (most recent call last):File "threading.py", line 932, in _bootstrap_innerFile "threading.py", line 870, in runFile "FFMPEGAudioEncoder.py", line 12297, in start_multi_file_processingUnboundLocalError:local variable 'output_file' referenced before assignment

**Comment by jlw4049** [comment]
Thanks for the bug report. I'm going to look into this tomorrow and I'll report back.

**Comment by peppersgc** [comment]
Sorry late getting back. Personal stuff got in the way. I figured out that it's specific files. I'll compress a couple and drop a link to them here ASAP.

**Comment by jlw4049** [comment]
Sounds great. Just give me some files to replicate the error so I can fix it. 

Thanks!

**Comment by peppersgc** [comment]
Close this, please. My laptop was destroyed in a car accident, and I can't remember the files. Sorry.

**Comment by jlw4049** [comment]
Sorry to hear about the car accident. 

I'll close this but if you ever come across it feel free to let me know.
