### ISSUE TITLE
Inverted Framerate Conversion Values

### ISSUE THREAD

**Issue by Jack1789** [jlw4049/FFMPEG-Audio-Encoder#41]
**Describe the bug**

While trying to convert an audio file using one fo the available options "23,976 > 24"
and viceversa, the resultan files will have not the desired timing according to the selected
option, but inverted ones. 

**To Reproduce**

So, to change a "23,976" framerate to a "24" one, the "24 > 23,976"
option must be chosen.

**Expected behavior**

The resultant files should have the expected right timing, according to what's
specified in the relevant menu options. 

**Screenshots**

 -

**Additional context**

I didn't tried with other framerates, but the issue might affect those as well.

Thanks.

**Comment by jlw4049** [comment]
I'm working on getting this fix out today

**Comment by jlw4049** [comment]
Fixed https://github.com/jlw4049/FFMPEG-Audio-Encoder/commit/b78790dd377c28919688067e9e301cbeb39448e1
