### ISSUE TITLE
[REQ] Update included Apps

### ISSUE THREAD

**Issue by Barough** [jlw4049/FFMPEG-Audio-Encoder#42]
What about updating the Apps that's FFMPEG-Audio-Encoder  is shipped with?

**Comment by jlw4049** [comment]
I'll do a sweep of tools and dependencies and provide an update

**Comment by Barough** [comment]
> I'll do a sweep of tools and dependencies and provide an update

Would be great if you could check the Apps each time before you make a new release. :)

**Comment by jlw4049** [comment]
Sounds good, I'll sort this and the other issue you made tomorrow and get a release out once I get up.

**Comment by jlw4049** [comment]
Fixed in v4.08 once it drops
