### ISSUE TITLE
QTFiles for QAAC

### ISSUE THREAD

**Issue by Barough** [jlw4049/FFMPEG-Audio-Encoder#45]
The easiest way to get the required QTFiles is to use nu774's 'makeportable2'.
https://sites.google.com/site/qaacpage/

Maybe include it in the QAAC folder and add a note how it works.
Download the latest iTunes
https://www.apple.com/itunes/download/win64
and then drag/drop it onto the makeportable2.cmd file
then wait for it to extract the required QTfiles folder

**Comment by jlw4049** [comment]
Done in latest release
