### ISSUE TITLE
QAAC Bitrate lost

### ISSUE THREAD

**Issue by deadlyshadow79** [jlw4049/FFMPEG-Audio-Encoder#47]
In QAAC setting page if CBR or ABR or CVBR is selected, there is no option to change Bitrate.
![Screenshot (1)](https://github.com/jlw4049/FFMPEG-Audio-Encoder/assets/52504665/c84c2f15-719e-4eda-8630-8f6a9320ee4e)

**Comment by jlw4049** [comment]
Was able to replicate it, I'll look this over today.
