### ISSUE TITLE
Error when trying to convert .m4a -> .mp3

### ISSUE THREAD

**Issue by Limboso** [jlw4049/FFMPEG-Audio-Encoder#48]
When I try to convert any .m4a file to .mp3 this error message appears

![image](https://github.com/jlw4049/FFMPEG-Audio-Encoder/assets/102487444/2a494b51-147e-48ea-a95f-3d1aac59fcaf)

**Comment by jlw4049** [comment]
Not able to reproduce. Can you give me the sample of one of the files that is causing you the issue?

**Comment by Limboso** [comment]
Yes, sure. It's also showing this traceback error window

![image](https://github.com/jlw4049/FFMPEG-Audio-Encoder/assets/102487444/79eb90b0-97fa-4d25-bf14-f945b9f0ee91)


[03 - Another Part of Me (Live At Wembley July 16, 1988).zip](https://github.com/jlw4049/FFMPEG-Audio-Encoder/files/13623415/03.-.Another.Part.of.Me.Live.At.Wembley.July.16.1988.zip)

**Comment by jlw4049** [comment]
> Yes, sure. It's also showing this traceback error window
> 
> ![image](https://github.com/jlw4049/FFMPEG-Audio-Encoder/assets/102487444/79eb90b0-97fa-4d25-bf14-f945b9f0ee91)
> 
> 
> [03 - Another Part of Me (Live At Wembley July 16, 1988).zip](https://github.com/jlw4049/FFMPEG-Audio-Encoder/files/13623415/03.-.Another.Part.of.Me.Live.At.Wembley.July.16.1988.zip)
> 

Sorry for the late response. I'll take a look at this tomorrow.

**Comment by jlw4049** [comment]
I still can't reproduce. Can you ensure you are using the FFMPEG version included with the program or update your FFMPEG version? 
There is something going on and I'm not sure it's code related. 

Additionally you are welcome to share with me your `config.ini` contents so I can see if something is wrong there.

**Comment by Limboso** [comment]
I just double checked the FFMPEG version and it's using the one bundled in the `FFMPEGAudioEncoder.v4.09.zip`

<details><summary>config.ini</summary>
<p>

[batch_path]
path = file input directory

[output_path]
path = F:\

[ffmpeg_path]
path = "F:\FFMPEGAudioEncoder.v4.09\Apps\FFMPEG\ffmpeg.exe"

[mpv_player_path]
path = "Apps\mpv\mpv.exe"

[mediainfogui_path]
path = "Apps\MediaInfo\MediaInfo.exe"

[fdkaac_path]
path = 

[qaac_path]
path = "Apps\qaac\qaac64.exe"
qt_path = "Apps\qaac\QTfiles64"

[debug_option]
option = Default

[auto_close_progress_window]
option = on

[audio_settings_command_toggle]
option = on

[save_window_locations]
ffmpeg audio encoder = yes
ffmpeg audio encoder position = 570x325+865+408
window location settings = yes
window location settings position = 
about = yes
about position = 
progress window = yes
progress window position = 711x392+26+26
job window = yes
job window position = 
display command = yes
display command position = 765x237+182+182
general settings = yes
general settings position = 640x670+640+205
batch window = yes
batch window position = 
audio window - aac = yes
audio window - aac - position = 
audio window - ac3 = yes
audio window - ac3 - position = 
audio window - e-ac3 = yes
audio window - e-ac3 - position = 
audio window - dts = yes
audio window - dts - position = 
audio window - opus = yes
audio window - opus - position = 
audio window - mp3 = yes
audio window - mp3 - position = 550x360+685+360
audio window - fdk-aac = yes
audio window - fdk-aac - position = 
audio window - qaac = yes
audio window - qaac - position = 
audio window - flac = yes
audio window - flac - position = 
audio window - alac = yes
audio window - alac - position = 
audio window - view streams = yes
audio window - view streams - position = 



</p>
</details> 

I tested with several other .m4a files and for all of them the same error is occurring

And this is another error window that is showing for me:

![image](https://github.com/jlw4049/FFMPEG-Audio-Encoder/assets/102487444/4659c751-375a-4353-b740-6885795d4a11)

**Comment by jlw4049** [comment]
Hmm, I need you to try a couple things for me. 

First thing, can you test any other codec to see if you're getting the same error?

Second thing, when encoding with mp3 can you go to **options, progress, degub**. Hopefully with this setting we will get more information about the root issue. 

Also are you on a 64 bit operating system?

**Comment by Limboso** [comment]
Wow! When I changed the `Progress Output ` to `Debug` option, it worked perfectly with no errors. 
![image](https://github.com/jlw4049/FFMPEG-Audio-Encoder/assets/102487444/dbcf839f-d7d8-4b18-8e50-547a0fc3d2e7)

But when I changed it back to the `Progress Bars` option the errors just came back
![image](https://github.com/jlw4049/FFMPEG-Audio-Encoder/assets/102487444/694cd0c7-982b-4c18-af25-d4cf62bac184)

And yes, I'm using a 64-bit OS

**Comment by jlw4049** [comment]
I've got another test build for you to do with normal progress bars enabled 

[FFMPEGAudioEncoder.zip](https://github.com/jlw4049/FFMPEG-Audio-Encoder/files/13665931/FFMPEGAudioEncoder.zip)

**Comment by Limboso** [comment]
Now it's working! I just tested with several different files and using different codecs with progress bars enabled and this time it went all good. No errors whatsoever!
![image](https://github.com/jlw4049/FFMPEG-Audio-Encoder/assets/102487444/294c0c9c-fb41-4f9b-84f7-db192440da63)


Thanks a lot for your time and patience!

**Comment by jlw4049** [comment]
I appreciate you testing things out for me. I'll officially release a fix in the coming days. It was odd I couldn't reproduce it on my own machines here. It seems like FFMPEG actually has changed their STDOUT output a little, where as before they just started it with 0's it now says N/A. This was causing a bug.

Anyways, feel free to use that build for **manual** jobs until I get the proper fix out for all jobs in the coming days.
