### ISSUE TITLE
[REQ] Update time?

### ISSUE THREAD

**Issue by Barough** [jlw4049/FFMPEG-Audio-Encoder#50]
Maybe time for an update....

FFmpeg v7.0
MediaInfo v24.0
MVP
QAAC v2.82

**Comment by jlw4049** [comment]
https://github.com/jlw4049/FFMPEG-Audio-Encoder/releases/tag/4.11

This is now completed, thanks for the reminder. If time/money allowed I'd add more features and other things to the software.
