### ISSUE TITLE
A suggestion.

### ISSUE THREAD

**Issue by serkan1247** [jlw4049/FFMPEG-Audio-Encoder#7]
First of all I wish you success.Do you consider to add the option to change audio frame rates ?

**Comment by jlw4049** [comment]
Let me look into this and I'll see what I can do

**Comment by BassThatHertz** [comment]
He probably means sample rate, frame rate applies to video only - it's the number of frames per second.

**Comment by jlw4049** [comment]
> He probably means sample rate (you can change this using the [`-ar` option](https://ffmpeg.org/ffmpeg.html#Audio-Options), e.g. `-ar 44100` to set the sample rate to 44.1 kHz). Frame rate applies to video only - it's the number of frames per second.

This is what I was thinking. 

In this case, the program already supports changing the sample rates to all supported sample rates per codec.

**Comment by jlw4049** [comment]
@serkan1247 If there is some other feature you would like added, feel free to start a new issue! I'm open to feedback!
